# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Foo:
  fields:
    default: bar
    form: bar
  order_by: 
  relationships: 
  filters: created_at
  search: 
  application: typus1

